spring:
  datasource:
    url: jdbc:mysql://mysql-seoul.ckrdfluznthc.ap-northeast-2.rds.amazonaws.com:3306/test?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
#  jackson:
#    serialization:
#      fail-on-empty-beans: false #빈값은 직렬화하지 않음
server:
  port: 8081